version: 2.1
parameters:
  image-tag:
    type: string
    default: "latest"
jobs:
  build:
    working_directory: ~/customer-microservice-main
    docker:
      - image: google/cloud-sdk
    IMAGETAG: << pipeline.parameters.image-tag >>
    steps:
      - checkout
