version: 2.1
jobs:
  build:
    working_directory: ~/customer-microservice-main
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: 
          name: printing parameter getting passed
          command: |
            echo ${name}
