version: 2.1
parameters:
  image-tag:
    type: string
    default: "latest"
jobs:
  build:
    working_directory: ~/test-dir
    docker:
      - image: google/cloud-sdk
    environment:
      IMAGETAG: << pipeline.parameters.image-tag >>
    steps:
      - checkout
      - run: 
        name: test parameter
        command: |
          echo {$IMAGETAG}
